<?php

namespace Heffe\SUFAPIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SteamUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SteamUserRepository extends EntityRepository
{
    /**
     * Create a SteamUser and persist it to the database
     *
     * @param string $steamId The SteamId of the SteamUser to create
     * @return SteamUser The newly created SteamUser object
     */
    public function createSteamUser($steamId)
    {
        $steamUser = new SteamUser();
        $steamUser->setSteamId($steamId);
        $steamUser->setDateCreated(new \DateTime());

        $this->_em->persist($steamUser);
        $this->_em->flush();

        return $steamUser;
    }
}
